// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:460171351409:web:c38da0f4efd2027d2ed2d0',
    messagingSenderId: '460171351409',
    projectId: 'md2-task-manager',
    authDomain: 'md2-task-manager.firebaseapp.com',
    storageBucket: 'md2-task-manager.firebasestorage.app',
    measurementId: 'G-8ZGXS202Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:460171351409:android:ae11e03882a1ab682ed2d0',
    messagingSenderId: '460171351409',
    projectId: 'md2-task-manager',
    storageBucket: 'md2-task-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:460171351409:ios:3e746cf062ed70752ed2d0',
    messagingSenderId: '460171351409',
    projectId: 'md2-task-manager',
    storageBucket: 'md2-task-manager.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:460171351409:ios:3e746cf062ed70752ed2d0',
    messagingSenderId: '460171351409',
    projectId: 'md2-task-manager',
    storageBucket: 'md2-task-manager.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:460171351409:web:5b44b04ee44075162ed2d0',
    messagingSenderId: '460171351409',
    projectId: 'md2-task-manager',
    authDomain: 'md2-task-manager.firebaseapp.com',
    storageBucket: 'md2-task-manager.firebasestorage.app',
    measurementId: 'G-Q5TRTMMK3P',
  );
}
